#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .tags.$$" EXIT
ctags --tag-relative -Rf./.git/.tags.$$ --exclude=.git --languages=+coffee,javascript,-sql --fields=+l
mv ./.git/.tags.$$ ./.git/tags
