#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  "${CTAGS:-ctags}" --tag-relative --fields=+l -L - -f"$dir/$$.tags" \
  --languages=+ruby,-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
